services:
  ubuntu:
    build:
      context: ./ubuntu
      dockerfile: Dockerfile
    container_name: ubuntu
    hostname: ubuntu
    privileged: true
    stdin_open: true
    tty: true
    networks:
      - ansible-net
    ports:
      - "2222:22"
    command: /usr/sbin/sshd -D

  centos:
    build:
      context: ./centos
      dockerfile: Dockerfile
    container_name: centos7
    hostname: centos
    privileged: true
    stdin_open: true
    tty: true
    networks:
      - ansible-net
    ports:
      - "2223:22"
    command: /usr/sbin/sshd -D

networks:
  ansible-net:
    driver: bridge
